name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install LaTeX
      run: sudo apt -y install texlive latexmk
    - name: Compile main.tex
      run: latexmk -pdf -interaction=batchmode main.tex
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout --orphan pdfs
        git add *.pdf
        git commit -m "Compile *.tex files"
        git push -f origin pdfs
