name: Compile all tex files
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prerun all .sh files in .github/workflows
      run: find .github/workflows -type f -name "*.sh" | sort | xargs -I % bash -c 'cd $(dirname %) && bash $(basename %)'


    - name: Get Cache Key
      id: get-cache-key
      run: |
        UBUNTU_PACKAGES=$(cat .github/workflows/UBUNTU_PACKAGES)
        CACHE_KEY=$(apt-cache policy $UBUNTU_PACKAGES | grep -oP "^[^ ]*:|(?<=Candidate: )[^ ]*" | tr -d '[:space:]')
        echo "::set-output name=key::$CACHE_KEY"
        echo "::set-output name=packages::$UBUNTU_PACKAGES"
    - name: Cache packages
      id: cache-packages
      uses: actions/cache@v2
      with:
        path: ~/packages-cache
        key: ${{ steps.get-cache-key.outputs.key }}
    - name: Install packages if not cached
      if: steps.cache-packages.outputs.cache-hit != 'true'
      env:
        UBUNTU_PACKAGES: ${{ steps.get-cache-key.outputs.packages }}
      run: |
        TF=$(mktemp)
        mkdir -p ~/packages-cache
        apt-get install -s $UBUNTU_PACKAGES | grep -oP "(?<=Inst )[^ ]*" > $TF
        sudo apt install -y $UBUNTU_PACKAGES
        cat $TF | xargs dpkg -L | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | grep -v "^/usr/share/doc/" | xargs cp --parents -t -P ~/packages-cache
    - name: Install packages if cached
      if: steps.cache-packages.outputs.cache-hit == 'true'
      run: sudo cp -v -f -r -P ~/packages-cache/* /
      
      
      
    - name: Run all executable .sh files
      run: find . -type f -not -path '*/\.*' -executable -name "*.sh" | sort | xargs -I % bash -c 'cd $(dirname %) && bash $(basename %)'
      
      
    - name: Compile all .tex files
      run: find . -type f -name "*.tex" -execdir latexmk -pdf -interaction=batchmode  {} \;
      
      
    - name: Commit pdfs with the same name as a tex file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        NEW_BRANCH=$(git rev-parse --abbrev-ref HEAD)-pdfs
        NEW_MESSAGE="$(git log -1 --pretty=%B) [generate pdfs branch]"
        git checkout --orphan $NEW_BRANCH
        git rm --cached -rf .
        find . -type f -name "*.tex" -execdir bash -c 'filename={};git add -f "${filename%.tex}.pdf";' \;
        git commit -m "$NEW_MESSAGE"
        git push -f origin $NEW_BRANCH
