name: Compile all tex files
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache LaTeX
      id: cache-latex
      uses: actions/cache@v2
      with:
        path: ~/latex-cache
        key: ${{ secrets.LATEX_PACKAGES }}
    - name: Install LaTeX if not cached
      if: steps.cache-primes.outputs.cache-hit != 'true'
      env:
        LATEX_PACKAGES: ${{ secrets.LATEX_PACKAGES }}
      run: |
        TF=$(mktemp)
        apt-get install -s $LATEX_PACKAGES | grep -oP "(?<=Inst )[^ ]*" > $TF
        sudo apt install -y $LATEX_PACKAGES
        cat $TF | xargs dpkg -L | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents -t ~/latex-cache
    - name: Install LaTeX if cached
      if: steps.cache-primes.outputs.cache-hit != 'false'
      run: sudo cp --verbose --force --recursive ~/latex-cache/* /
      
    - name: Compile all .tex files
      run: find . -type f -name "*.tex" -execdir latexmk -pdf -interaction=batchmode  {} \;
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout --orphan pdfs
        git rm --cached -rf .
        find . -type f -name "*.tex" -execdir bash -c 'filename={};git add -f "${filename%.tex}.pdf";' \;
        git commit -m "Compile *.tex files"
        git push -f origin pdfs
