name: Compile all tex files
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install LaTeX
      run: sudo apt -y install texlive-latex-extra latexmk
    - name: Compile all .tex files
      run: find . -type f -name "*.tex" -execdir latexmk -pdf -interaction=batchmode  {} \;
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout --orphan pdfs
        git rm --cached -rf .
        find . -type f -name "*.tex" -execdir bash -c 'filename={};git add -f "${filename%.tex}.pdf";' \;
        git commit -m "Compile *.tex files"
        git push -f origin pdfs
